import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About page title",
  description: "Generated by Next.js",
};

export default function About() {
  return <div>About</div>;
}
